version: '3'
services:
  framework:
    build: ../framework
    image: fdudatamining:framework
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - database:/var/lib/mysql/data
    ports:
      - 3306:3306
  web:
    image: nginx:alpine
    depends_on:
      - framework
      - phpmyadmin
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD
    depends_on:
      - database
    external_links:
      - database:db
    volumes:
      - session:/session
    ports:
      - 8080:80
  # NOTE: https://github.com/docker/compose/issues/1896
  #       No way to implement this yet in a more convinient way
  # data:
  #   build: ../data
  #   image: fdudatamining:data
  #   environment:
  #     - MYSQL_HOST=database
  #     - MYSQL_ROOT_PASSWORD
  #   depends_on:
  #     - database
  #   volumes:
  #     - data:/root
volumes:
  data:
  database:
  session:
