version: '3'
services:
  framework:
    build: ../framework
    image: fdudatamining:framework
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - data:/var/lib/mysql/data
    ports:
      - 3306:3306
  web:
    image: nginx:alpine
    depends_on:
      - framework
      - phpmyadmin
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD
    external_links:
      - database:db
    volumes:
      - session:/session
    ports:
      - 8080:80
  data:
    build: ../data
    image: fdudatamining:data
    environment:
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD
    depends_on:
      - database
volumes:
  data:
  session:
